export enum COMMON_ERRORS {
  LANGUAGE_PREFIX = 'common',
  NOT_FOUND = 'NOT_FOUND',
  BAD_USER_INPUT = 'BAD_USER_INPUT',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  PHONE_EXITS = 'PHONE_EXITS',
  SOME_INPUT_DATA_INCORRECT = 'SOME_INPUT_DATA_INCORRECT',
}
